// questions.js — Practice mode question bank (offline, no server needed)

export const PRACTICE_QUESTIONS = [
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/500px-African_Bush_Elephant.jpg", options: ["Rhinoceros", "Elephant", "Hippopotamus", "Zebra"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/500px-Giraffe_Mikumi_National_Park.jpg", options: ["Zebra", "Giraffe", "Camel", "Ostrich"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Emperor_Penguin_Manchot_empereur.jpg", options: ["Puffin", "Penguin", "Duck", "Dolphin"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Greater_flamingo_%28Phoenicopterus_roseus%29.jpg/500px-Greater_flamingo_%28Phoenicopterus_roseus%29.jpg", options: ["Parrot", "Flamingo", "Toucan", "Eagle"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/960px-Tursiops_truncatus_01.jpg", options: ["Whale", "Dolphin", "Shark", "Seal"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Kangaroo_and_joey03.jpg/500px-Kangaroo_and_joey03.jpg", options: ["Wallaby", "Kangaroo", "Wombat", "Koala"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Giant_Panda_2004-03-2.jpg/960px-Giant_Panda_2004-03-2.jpg", options: ["Bear", "Panda", "Koala", "Raccoon"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Plains_Zebra_Equus_quagga.jpg/500px-Plains_Zebra_Equus_quagga.jpg", options: ["Horse", "Zebra", "Donkey", "Giraffe"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Octopus2.jpg/960px-Octopus2.jpg", options: ["Jellyfish", "Octopus", "Starfish", "Crab"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Peacock_Plumage.jpg/960px-Peacock_Plumage.jpg", options: ["Pheasant", "Peacock", "Turkey", "Crane"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Koala_climbing_tree.jpg/960px-Koala_climbing_tree.jpg", options: ["Lemur", "Koala", "Panda", "Sloth"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Bradypus_variegatus.jpg/960px-Bradypus_variegatus.jpg", options: ["Koala", "Sloth", "Lemur", "Monkey"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Igel.JPG/960px-Igel.JPG", options: ["Mouse", "Hedgehog", "Shrew", "Mole"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Hippocampus.jpg/500px-Hippocampus.jpg", options: ["Pipefish", "Seahorse", "Fish", "Shrimp"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/1/11/Ramphastos_toco.jpg", options: ["Parrot", "Toucan", "Woodpecker", "Macaw"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Mountain_Gorilla.jpg/500px-Mountain_Gorilla.jpg", options: ["Chimpanzee", "Gorilla", "Monkey", "Gibbon"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ursus_maritimus_Steve_Amstrup.jpg/960px-Ursus_maritimus_Steve_Amstrup.jpg", options: ["Grizzly Bear", "Polar Bear", "Panda", "Seal"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Bubo_virginianus_06.jpg/500px-Bubo_virginianus_06.jpg", options: ["Hawk", "Owl", "Eagle", "Falcon"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/AxolotlBE.jpg", options: ["Salamander", "Axolotl", "Newt", "Tadpole"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Ornithorhynchus.jpg/960px-Ornithorhynchus.jpg", options: ["Mongoose", "Platypus", "Otter", "Mole"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Porcupine-BioDome.jpg/500px-Porcupine-BioDome.jpg", options: ["Mouse", "Porcupine", "Squirrel", "Mole"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Nine-banded_Armadillo.jpg/960px-Nine-banded_Armadillo.jpg", options: ["Anteater", "Armadillo", "Aardvark", "Badger"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Asterias_rubens.jpg/960px-Asterias_rubens.jpg", options: ["Sea Urchin", "Starfish", "Jellyfish", "Clam"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Ceratotherium_simum.jpg/960px-Ceratotherium_simum.jpg", options: ["Hippopotamus", "Rhinoceros", "Elephant", "Anteater"], correct: 1 },
  { text: "What animal is this?", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Hippo_at_dawn.jpg/960px-Hippo_at_dawn.jpg", options: ["Rhinoceros", "Hippopotamus", "Elephant", "Seal"], correct: 1 },
];
